version: '3.3'
services:
  backend1:
    image: polarlightning/bitcoind:24.0
    container_name: polar-n3-backend1
    environment:
      USERID: ${USERID:-1000}
      GROUPID: ${GROUPID:-1000}
    hostname: backend1
    command: >-
      bitcoind -server=1 -regtest=1
      -rpcauth=polaruser:5e5e98c21f5c814568f8b55d83b23c1c$$066b03f92df30b11de8e4b1b1cd5b1b4281aa25205bd57df9be82caf97a05526
      -debug=1 -zmqpubrawblock=tcp://0.0.0.0:28334
      -zmqpubrawtx=tcp://0.0.0.0:28335 -zmqpubhashblock=tcp://0.0.0.0:28336
      -txindex=1 -dnsseed=0 -upnp=0 -rpcbind=0.0.0.0 -rpcallowip=0.0.0.0/0
      -rpcport=18443 -rest -listen=1 -listenonion=0 -fallbackfee=0.0002
      -blockfilterindex=1 -peerblockfilters=1
    volumes:
      - ./volumes/bitcoind/backend1:/home/bitcoin/.bitcoin
    expose:
      - '18443'
      - '18444'
      - '28334'
      - '28335'
    ports:
      - '18443:18443'
      - '19444:18444'
      - '28334:28334'
      - '29335:28335'
      
  bob:
    image: polarlightning/clightning:23.02.2
    container_name: polar-n3-bob
    environment:
      USERID: ${USERID:-1000}
      GROUPID: ${GROUPID:-1000}
    hostname: bob
    command: >-
      lightningd --alias=bob --addr=bob --addr=0.0.0.0:9735 --network=regtest
      --bitcoin-rpcuser=polaruser --bitcoin-rpcpassword=polarpass
      --bitcoin-rpcconnect=polar-n3-backend1 --bitcoin-rpcport=18443
      --log-level=debug --dev-bitcoind-poll=2 --dev-fast-gossip
      --grpc-port=11001 --plugin=/opt/c-lightning-rest/plugin.js
      --plugin=/plugins/prism.py
      --rest-port=8080 --rest-protocol=http
    restart: always
    volumes:
      - ./volumes/c-lightning/bob/lightningd:/home/clightning/.lightning
      - ./volumes/c-lightning/bob/rest-api:/opt/c-lightning-rest/certs
      - ./plugins:/plugins:rw
    expose:
      - '8080'
      - '11001'
      - '9735'
    ports:
      - '8182:8080'
      - '11002:11001'
      - '9836:9735'