version: '3.3'
services:
  alice:
    image: polarlightning/clightning:23.02.2
    container_name: polar-n3-alice
    environment:
      USERID: ${USERID:-1000}
      GROUPID: ${GROUPID:-1000}
    hostname: alice
    command: >-
      sh -c "pip install pyln-client && lightningd --alias=alice --addr=alice --addr=0.0.0.0:9735 --network=regtest
      --bitcoin-rpcuser=polaruser --bitcoin-rpcpassword=polarpass
      --bitcoin-rpcconnect=polar-n3-backend1 --bitcoin-rpcport=18443
      --log-level=debug --dev-bitcoind-poll=2 --dev-fast-gossip
      --grpc-port=11001 --plugin=/plugins/prism.py"
    restart: always
    volumes:
      - ./volumes/c-lightning/alice/lightningd:/home/clightning/.lightning/
      - ./volumes/c-lightning/alice/rest-api:/opt/c-lightning-rest/certs
      - ./plugins:/plugins:rw
      - ./certs:/certs:rw
    expose:
      - '8080'
      - '11001'
      - '9735'
    ports:
      - '8183:8080'
      - '11003:11001'
      - '9837:9735'
    networks:
      3_default:

networks:
  3_default:
    external: true